COHERE_API_KEY = "LMLBqRuw26eAVEGk5r89WchK3tP8cNGV3EGt9xSC"

QDRANT_HOST = "https://046843ec-e71e-4ab6-9100-711d8c1ee55b.us-east4-0.gcp.cloud.qdrant.io"
QDRANT_API_KEY = "u-g6fMdlAHQzNEH16uAZrkB1Fw1N4W9pqLwqrXJYwAWRsk2aHCzn3w" 
